import { Equipment } from "@/types";
// subcategory: "Excavators",
export const MOCK_EQUIPMENT: Equipment[] = [
    {
        id: "eq-1",
        name: "Caterpillar 320 Excavator",
        description: "حفار كاتربيلر بحالة ممتازة، جاهز للمشاريع الكبيرة. صيانة دورية بالوكيل.",
        status: "available",
        sectors: ["Construction", "Mining"],
        category: "Heavy Machinery",
        dailyRate: 1500,
        monthlyRate: 35000,
        media: ["/images/equipment/CAT Excavator 320.jfif"],
        brand: "CAT",
        model: "320D",
        manufacturingYear: 2022,
        powerCapacity: "150 HP",
        fuelType: "Diesel",
        withOperator: true,
        operatorCost: 200,
        location: "Riyadh",
        ownerId: 101,
        createdAt: "2024-01-01",
        updatedAt: "2024-01-15",
        latitude: 21.5225,
        longitude: 39.1817,
        frequencyRent: "Daily",
    },
    {
        id: "eq-2",
        name: "Komatsu D85 Dozer",
        description: "بلدوزر كوماتسو قوي لأعمال التسوية وتمهيد الطرق.",
        status: "rented",
        sectors: ["Construction", "Transportation"],
        category: "Earthmovers",
        dailyRate: 2200,
        media: ["/images/equipment/Komatsu Dozer D85-1.jpg"],
        brand: "Komatsu",
        model: "D85-EX",
        manufacturingYear: 2021,
        withOperator: false,
        location: "Jeddah",
        ownerId: 102,
        createdAt: "2024-01-05",
        updatedAt: "2024-01-20",
        latitude: 21.5225,
        longitude: 39.1817,
        frequencyRent: "Daily",
    },
    {
        id: "eq-3",
        name: "Perkins Generator 500KVA",
        description: "مولد كهرباء 500 كيلو فولت أمبير كاتم للصوت.",
        status: "available",
        sectors: ["Industrial", "Construction", "Oil & Gas"],
        category: "Generators",
        dailyRate: 400,
        media: ["/images/equipment/Perkins Generator 500KVA.jpg"],
        brand: "Perkins",
        model: "P500",
        manufacturingYear: 2023,
        fuelType: "Diesel",
        withOperator: false,
        location: "Dammam",
        ownerId: 103,
        createdAt: "2024-02-01",
        updatedAt: "2024-02-01",
        latitude: 21.5225,
        longitude: 39.1817,
        frequencyRent: "Monthly",
    },
    {
        id: "eq-4",
        name: "Bobcat S450 Skid Steer",
        description: "بوبكات صغير للأماكن الضيقة وأعمال التحميل.",
        status: "maintenance",
        sectors: ["Construction", "Agricultural"],
        category: "Loaders",
        dailyRate: 600,
        media: ["/images/equipment/Bobcat S540.webp"],
        brand: "Bobcat",
        model: "S540",
        manufacturingYear: 2020,
        withOperator: true,
        location: "Riyadh",
        ownerId: 101,
        createdAt: "2024-01-10",
        updatedAt: "2024-01-12",
        latitude: 21.5225,
        longitude: 39.1817,
        frequencyRent: "Yearly",
    },
    {
        id: "eq-5",
        name: "Liebherr Mobile Crane",
        description: "رافعة متحركة 50 طن لرفع المواد الثقيلة.",
        status: "available",
        sectors: ["Construction", "Industrial"],
        category: "Cranes",
        dailyRate: 3500,
        media: ["/images/equipment/Liebherr-Mobile-Crane.jpg"],
        brand: "Liebherr",
        model: "LTM 1050",
        manufacturingYear: 2019,
        withOperator: true,
        location: "Neom",
        ownerId: 104,
        createdAt: "2024-01-15",
        updatedAt: "2024-01-15",
        latitude: 21.5225,
        longitude: 39.1817,
        frequencyRent: "Yearly",
    }
];